### ISSUE TITLE
Allow export of figures/data from reports

### ISSUE THREAD

**Issue by rambaut** [artic-network/civet#101]
It would be possible to have buttons on the report to export CSV data files (for each table) and SVG/PNG for each of the figures. This is related to issue #99

**Comment by aineniamh** [comment]
snipit export now enabled, timeline previously enabled. CSV to come.

**Comment by aineniamh** [comment]
![Screenshot 2021-07-28 at 15 00 34](https://user-images.githubusercontent.com/11678307/127335631-ce839caf-2306-4cef-b0d6-4a7656286dfc.png)
Export to clipboard, csv or print query table now enabled.
