### ISSUE TITLE
error written to report if process trys to pull a sequence from cog that has failed the qc

### ISSUE THREAD

**Issue by richardemyers** [artic-network/civet#11]
Report generated has a key error when sequence has failed qc and an attempt is made to retrieve it from the cog data set

![Screenshot from 2020-06-14 16-21-37](https://user-images.githubusercontent.com/18465966/84597351-533d3a80-ae5b-11ea-8533-53b812b7cb59.png)

**Comment by aineniamh** [comment]
I've re-worked this and think it's working now. I'll test it more tomorrow with some example sequences, but if you still get this issue just let me know.
