### ISSUE TITLE
definition of identifiers

### ISSUE THREAD

**Issue by richardemyers** [artic-network/civet#12]
process appears to work where sequences are referenced in alignments etc by COG_ID, some of PHE's sequences are in these datasets with a 9-11 digit identifier, rather than the cog id.

The tool is unable to find these sequences in datasets and deems them missing

**Comment by aineniamh** [comment]
Yes, you're right that by default we're just looking to match the COG-ID. Some of the sequences in the database do have a COG-ID in this format: `England/20121234567/2020` and should match with a query string `20121234567`. 

Andrew mentioned there may be a `h` in the query string? Is this the case? We can add in some flexibility to the search and if there are other fields that would be useful to search the metadata for I can write that in. For instance if "lab_id" would be useful we can include that?

**Comment by richardemyers** [comment]
thanks for getting back, i'd assumed that it was taking the field between the Engand/ and /2020 as the identifier and as you say PHE has this mixed model. If i use the numeric string in the sample sheet it doesn't match it. I haven't tried with the H included - because i couldn't see any way that that would work. 
Haven't look to see how that matching is costructed - but perhaps the fact that it is all numeric causes string matching issues?
i ran some hideous sed hackery on a local copy of the civet cat data to to swap the numeric bit with the cog id and was able to find the samples i expected. From my point of view i would be happy with just being able to use the COGID (PHEC-[xxxxx] in our case) to find samples, regardless of how the sequences are labelled.

**Comment by richardemyers** [comment]
sorry - to be clearer a sample labelled in the alignments/trees etc as England/20121234567/2020 will also have a correcttly formed cog id  of form PHEC-12345 - the numeric part in the identifier above (20121234567) refers to our lims id - which as Andrew states would have an H at the front.

**Comment by aineniamh** [comment]
Ah of course I see what you mean. The search that is currently performed would match the COG id, rather than anything else, but I can add in a search for different fields too, whichever fields are most useful/ accesible to you.

I will change to seach for:
```
central_sample_id (COG-ID),
biosample_source_id 
```

But if there's anything else you think would be a useful field to match on, just let me know and I can add in more.

**Comment by richardemyers** [comment]
sounds good- i think as long as the cog id works we should be fine

**Comment by aineniamh** [comment]
This is now implemented, will search for the COG-id, but also has an optional `--search-field` flag that lets you search the metadata for another field (e.g. sequence_name, biosample_source_id)
