### ISSUE TITLE
trees are too thin?

### ISSUE THREAD

**Issue by omarkr8** [artic-network/civet#148]
Hi, 

By thin, i mean visually. I know we can expand the tree vertically, but all my nodes seem to be compressed all the way to the left, as if the branch lengths are tiny. If i am really precise, i can click and collapse branches, but these do not make good figures.
they basically look like all the nodes are on a single straight string. Am unsure if my input/background diversity affects it? do I need a certain range of SNPs to make the branches extend

![tree1](https://user-images.githubusercontent.com/80584966/147526170-23f6558e-655b-4b7d-9abb-160e0d8513d3.JPG)

![tree2](https://user-images.githubusercontent.com/80584966/147526177-1d36f865-0908-4cc4-9232-8414d933c294.JPG)

**Comment by omarkr8** [comment]
Turns out its a browser thing?
viewing the html on my WSL gave me those thin trees, but viewing it back on windows gave me properly spaced branches. 
strange but otherwise non-issue.

**Comment by rambaut** [comment]
Thanks. There may be some HTML layout issues on some browsers and also some screen sizes.
