### ISSUE TITLE
search for mutations of interest

### ISSUE THREAD

**Issue by omarkr8** [artic-network/civet#157]
Just a question. 

The papers says we can specify mutations (nucleotide and amino acid) to focus on the tree?

Which options are related to this? and what needs to be supplied? 
im guessing its possible to make a specific snipit figure to show just our loci of interest?

**Comment by aineniamh** [comment]
Ah, sorry I missed this issue before! Internally, civet will run scorpio and type each of your sequences in turn for the mutations of interest (so if you specified S:N501Y, it would check for them in your sequences). It then adds a column to the output metadata with the genotype at that point for each sequence and will annotate the tips of the output phylogeny with the genotype of each sequence. You can then colour the tree by the genotype as well to help highlight that SNP occurance accross your sequences. 

An example of this can be found here: https://cov-lineages.org/resources/civet/civet_case_study_2.html
