### ISSUE TITLE
gofasta dist-push error

### ISSUE THREAD

**Issue by rjorton** [artic-network/civet#161]
is civet 3 incompatible with the latest version of gofasta? We have civet3 installed onto a ubuntu VirtualMachine via GitHub download and install, testing with a single sequence query against a small set of (non-COG) target seqs. Keep getting the following error:

Error: invalid argument "--dist-up" for "--dist-push" flag: strconv.ParseInt: parsing "--dist-up": invalid syntax

Looks like the civet.smk file for the rule "find_catchment" does not give --dist-push an argument, but think gofasta now expects one for this

**Comment by aineniamh** [comment]
Thanks for flagging this- I wasn't aware the gofast behaviour had changed, but I've modified the environment file to specifiy a particular version for the moment. I'll move to incorporate the new behaviour soon after I've had a chance to test it out, but this should be resolved with the latest env change now!
