### ISSUE TITLE
Incorrect display of percentage  of Ns in report file

### ISSUE THREAD

**Issue by thanhleviet** [artic-network/civet#21]
Hi,

The report of sequence having too many Ns like this: `Sequence has too many Ns: 0.9% of bases`
It should be 90% instead.

My quick fix locally was: 

` final_reason = "Sequence has too many Ns: " + str(float(n_content)*100) + "\% of bases  "`

Maybe this looks cleaner

`  final_reason = f"Sequence has too many Ns:  {n_content*100}\% of bases  " `

Also adding 2 spaces after the "of bases"  will create break line for each sample.

Thanks

**Comment by ViralVerity** [comment]
thanks for finding that! Fixed
