### ISSUE TITLE
Running on climb

### ISSUE THREAD

**Issue by josephhughes** [artic-network/civet#26]
I've tried this on CLIMB:

`(civet) [climb-covid19-hughesj@bham civet]$ civet --CLIMB civet/tests/test.csv --fasta civet/tests/test.fasta `

But get this:

```
Input fasta file: /cephfs/covid/bham/climb-covid19-hughesj/civet/civet/tests/test.fasta
Output files will be written to /cephfs/covid/bham/climb-covid19-hughesj/civet/2020-06-18-154932313

Input file: /cephfs/covid/bham/climb-covid19-hughesj/civet/civet/tests/test.csv
No fields to colour by provided, will colour by adm1 by default.

COG-UK ids to process:
EDB129_closest
EDB129_closestb
20144000304_closest
This_seq_is_too_short
EDB3588
EDB2533
PHEC-1A65C
PHEC-1AD2A
PHEC-1A917
This_seq_has_lots_of_Ns
This_seq_is_literally_just_N


Number of threads: 1

Error: no way to find source data.

To run civet please either
1) ssh into CLIMB and run with --CLIMB flag
2) Run using `--remote-sync` flag and your CLIMB username specified e.g. `-uun climb-covid19-otoolexyz`
3) Specify a local directory with the appropriate files on. The following files are required:
    - cog_global_tree.nexus
    - cog_metadata.csv
    - cog_metadata_all.csv
    - cog_global_metadata.csv
    - cog_global_alignment.fasta
    - cog_alignment.fasta

```

Is that the correct command for running it on CLIMB?

**Comment by aineniamh** [comment]
Ah yes. 😅  That is the correct way of doing it, but I have literally never tested civet on CLIMB, so I'm not surprised it doesn't work. I can see the bug, give me a couple of minutes and I'll fix it!

**Comment by aineniamh** [comment]
Okay, that should be fixed now, but it'll need to be updated on CLIMB.

**Comment by josephhughes** [comment]
Not quite sorted yet.

**Comment by aineniamh** [comment]
So, I've installed onto climb myself now and it's working for me with the test data! I was a bit over-zealous with my error catching, but I've sorted that now.🤞  I'm going to close the issue and I hope that works for you. If not just let me know and I'll reopen.
