### ISSUE TITLE
The rule iqtree_catchment crashes when input alignment is not properly aligned

### ISSUE THREAD

**Issue by thanhleviet** [artic-network/civet#27]
Hi,

This rule crashed when:

-  input alignment was not properly aligned/ formatted, ie. 1 sequence with length 29901 while the others had 29903 of bases
- alignment with less than 4 sequences and iqtree complained about using boostrap 

My quick and dirty fix for these:

```python

        if taxa != aln_taxa:
            # Re-align to fix alignment 
            shell("mv {input.aln:q} tmp.fa")
            shell("mafft --auto tmp.fa > {input.aln:q}")
            if aln_taxa > 4:
                shell("iqtree -s {input.aln:q} -bb 1000 -au -m HKY -nt 1 -redo")
            else:
                shell("iqtree -s {input.aln:q} -au -m HKY -nt 1 -redo")
```

**Comment by aineniamh** [comment]
Hi, there *shouldn't* be an issue with input as the sequences don't have to be aligned- we map them and pad against a reference [here](https://github.com/COG-UK/civet/blob/33afd9b87f7729a816152d87b17b5eac0c2de024/civet/scripts/find_closest_cog.smk#L38). Would you be able to provide an example of where an input sequence has not aligned properly? 

Thanks for pointing out the <4 issue and in fact, we mightn't necessarily need to bootstrap in these local trees anyway so I can make that change.

**Comment by aineniamh** [comment]
I found where this was breaking! As it turns out I was running the padding against the reference, but the unpadded version was being taken downstream, rather than the correct one! 

I've also now removed the bootstrapping from the tree as we're not currently displaying those values anyway.

Thanks for pointing these out!
