### ISSUE TITLE
Possible enhancement: details of the counts for for each country when sequences are identical

### ISSUE THREAD

**Issue by josephhughes** [artic-network/civet#28]
Would be nice to have the details of how the sequences are distributed between the countries. Instead of 194 nodes in Netherlands, UK, USA, actually providing for example 94 Netherland, 36 UK, 50 USA ... at least the top countries.
Or even better, some mini-barplot at the tips to illustrate the distribution, something like:
http://etetoolkit.org/static/img/gallery/barchart400x400.png

**Comment by ViralVerity** [comment]
yeah that sounds like a good plan - I can certainly add in the numbers, I'll take a look at adding the mini barplots!

**Comment by ViralVerity** [comment]
In the most recent commit, there are bar plots at the end of the report to describe the top ten countries in each collapsed node
