### ISSUE TITLE
Feature Request: Export SNIPIT

### ISSUE THREAD

**Issue by mattloose** [artic-network/civet#99]
In civet3 it would be great to have a button to export SVG (or PNG etc) of a SNIPIT plot - it appears to now be dumped into the html as pure SVG so can be grabbed that way, but  would be useful to grab in other forms.

Thanks.

**Comment by rambaut** [comment]
Perhaps that is `decaf_skinny`?

**Comment by mattloose** [comment]
or diet_caffeine_free_coke

**Comment by aineniamh** [comment]
Have added in a snipit svg and png export button to the report- svg working fine, but png a little tricky to size it sensibly so that's still a bit of a work in progress.

**Comment by mattloose** [comment]
Lovely stuff - I will try this out shortly!
